export const EVENT_ON_MOUNT_BIG_SCREEN = 'EVENT_ON_MOUNT_BIG_SCREEN',
    EVENT_ON_MOUNT_BIG_SCREEN_REVERSE = 'EVENT_ON_MOUNT_BIG_SCREEN_REVERSE',
    EVENT_REMOVE_BIG_SCREEN_LISTENER = 'EVENT_REMOVE_BIG_SCREEN_LISTENER',
    EVENT_REMOVE_BIG_SCREEN_REVERSE_LISTENER = 'EVENT_REMOVE_BIG_SCREEN_REVERSE_LISTENER',
    EVENT_REMOVE_BIG_SCREEN_LISTENERS = 'EVENT_REMOVE_BIG_SCREEN_LISTENERS',

    EVENT_ON_MOUNT_SMALL_SCREEN = 'EVENT_ON_MOUNT_SMALL_SCREEN',
    EVENT_ON_MOUNT_SMALL_SCREEN_REVERSE = 'EVENT_ON_MOUNT_SMALL_SCREEN_REVERSE',
    EVENT_REMOVE_SMALL_SCREEN_LISTENER = 'EVENT_REMOVE_SMALL_SCREEN_LISTENER',
    EVENT_REMOVE_SMALL_SCREEN_REVERSE_LISTENER = 'EVENT_REMOVE_SMALL_SCREEN_REVERSE_LISTENER',
    EVENT_REMOVE_SMALL_SCREEN_LISTENERS = 'EVENT_REMOVE_SMALL_SCREEN_LISTENERS',

    EVENT_REMOVE_SCREEN_LISTENERS = 'EVENT_REMOVE_SCREEN_LISTENERS'

export const EVENT_ON_MOUNT_HOVERABLE = 'EVENT_ON_MOUNT_HOVERABLE',
    EVENT_ON_MOUNT_HOVERABLE_REVERSE = 'EVENT_ON_MOUNT_HOVERABLE_REVERSE',
    EVENT_REMOVE_HOVERABLE_LISTENER = 'EVENT_REMOVE_HOVERABLE_LISTENER',
    EVENT_REMOVE_HOVERABLE_REVERSE_LISTENER = 'EVENT_REMOVE_HOVERABLE_REVERSE_LISTENER',
    EVENT_REMOVE_HOVERABLE_LISTENERS = 'EVENT_ON_MOUNT_HOVERABLE_LISTENERS'

export const EVENT_ON_MOUNT_TOUCHABLE = 'EVENT_ON_MOUNT_TOUCHABLE',
    EVENT_ON_MOUNT_TOUCHABLE_REVERSE = 'EVENT_ON_MOUNT_TOUCHABLE_REVERSE',
    EVENT_REMOVE_TOUCHABLE_LISTENER = 'EVENT_REMOVE_TOUCHABLE_LISTENER',
    EVENT_REMOVE_TOUCHABLE_REVERSE_LISTENER = 'EVENT_REMOVE_TOUCHABLE_REVERSE_LISTENER',
    EVENT_REMOVE_TOUCHABLE_LISTENERS = 'EVENT_REMOVE_TOUCHABLE_LISTENERS'

export const EVENT_NAVIGATING = 'EVENT_NAVIGATING',
    EVENT_NAVIGATED = 'EVENT_NAVIGATED'

export const EVENT_PERFORM_RIPPLE_EFFECT = 'EVENT_PERFORM_RIPPLE_EFFECT'

export const EVENT_OPEN_LAMP = 'EVENT_OPEN_LAMP',
    EVENT_CLOSE_LAMP = 'EVENT_CLOSE_LAMP'

export const EVENT_OPEN_MODAL = 'EVENT_OPEN_MODAL',
    EVENT_CLOSE_LAST_MODAL = 'EVENT_CLOSE_LAST_MODAL',
    EVENT_CLOSE_ALL_MODALS = 'EVENT_CLOSE_ALL_MODALS'

export const EVENT_ADD_INTERSECTION_OBSERVER = 'EVENT_ADD_OBSERVER',
    EVENT_REMOVE_INTERSECTION_OBSERVER = 'EVENT_REMOVE_OBSERVER'

export const EVENT_LOAD_LAZY_IMAGE = 'EVENT_LOAD_LAZY_IMAGE'

export const EVENT_SLIDER_LOADED = 'EVENT_SLIDER_NAVIGATION_LOAD',
    EVENT_SLIDER_NAVIGATION_TO_PREV = 'EVENT_SLIDER_NAVIGATION_TO_PREV',
    EVENT_SLIDER_NAVIGATION_TO_NEXT = 'EVENT_SLIDER_NAVIGATION_TO_NEXT',
    EVENT_SLIDER_SLIDE_TO_INDEX = 'EVENT_SLIDE_TO_INDEX',
    EVENT_SLIDER_INDEX_CHANGED = 'EVENT_SLIDER_INDEX_CHANGED',
    EVENT_SLIDER_INSERT_ELEMENTS_FOR_INFINITY = 'EVENT_SLIDER_INSERT_ELEMENTS_FOR_INFINITE'