export const EVENT_ON_MOUNT_BIG_SCREEN = 'EVENT_ON_MOUNT_BIG_SCREEN',
    EVENT_ON_MOUNT_BIG_SCREEN_REVERSE = 'EVENT_ON_MOUNT_BIG_SCREEN_REVERSE',
    EVENT_REMOVE_BIG_SCREEN_LISTENERS = 'EVENT_REMOVE_BIG_SCREEN_LISTENERS',
    EVENT_ON_MOUNT_SMALL_SCREEN = 'EVENT_ON_MOUNT_SMALL_SCREEN',
    EVENT_ON_MOUNT_SMALL_SCREEN_REVERSE = 'EVENT_ON_MOUNT_SMALL_SCREEN_REVERSE',
    EVENT_REMOVE_SMALL_SCREEN_LISTENERS = 'EVENT_REMOVE_SMALL_SCREEN_LISTENERS',
    EVENT_REMOVE_SCREEN_LISTENERS = 'EVENT_REMOVE_SCREEN_LISTENERS',
    EVENT_ON_BIG_SCREEN = 'EVENT_ON_BIG_SCREEN',
    EVENT_ON_SMALL_SCREEN = 'EVENT_ON_SMALL_SCREEN'

export const EVENT_ON_MOUNT_HOVERABLE = 'EVENT_ON_MOUNT_HOVERABLE',
    EVENT_ON_MOUNT_HOVERABLE_REVERSE = 'EVENT_ON_MOUNT_HOVERABLE_REVERSE',
    EVENT_REMOVE_HOVERABLE_LISTENERS = 'EVENT_ON_MOUNT_HOVERABLE_LISTENERS'

export const EVENT_NAVIGATING = 'EVENT_NAVIGATING',
    EVENT_NAVIGATED = 'EVENT_NAVIGATED'

export const EVENT_PERFORM_RIPPLE_EFFECT = 'EVENT_PERFORM_RIPPLE_EFFECT'

export const EVENT_OPEN_LAMP = 'EVENT_OPEN_LAMP',
    EVENT_CLOSE_LAMP = 'EVENT_CLOSE_LAMP'

export const EVENT_OPEN_MODAL = 'EVENT_OPEN_MODAL',
    EVENT_CLOSE_LAST_MODAL = 'EVENT_CLOSE_LAST_MODAL',
    EVENT_CLOSE_ALL_MODALS = 'EVENT_CLOSE_ALL_MODALS'