export const EVENT_ADD_LISTENER_BIG_SCREEN = 'EVENT_ADD_LISTENER_BIG_SCREEN',
    EVENT_ADD_LISTENER_BIG_SCREEN_REVERSE = 'EVENT_ADD_LISTENER_BIG_SCREEN_REVERSE',
    EVENT_REMOVE_LISTENER_BIG_SCREEN = 'EVENT_REMOVE_LISTENER_BIG_SCREEN',
    EVENT_REMOVE_LISTENER_BIG_SCREEN_REVERSE = 'EVENT_REMOVE_LISTENER_BIG_SCREEN_REVERSE',
    EVENT_REMOVE_LISTENERS_BIG_SCREEN = 'EVENT_REMOVE_LISTENERS_BIG_SCREEN',

    EVENT_ADD_LISTENER_SMALL_SCREEN = 'EVENT_ADD_LISTENER_SMALL_SCREEN',
    EVENT_ADD_LISTENER_SMALL_SCREEN_REVERSE = 'EVENT_ADD_LISTENER_SMALL_SCREEN_REVERSE',
    EVENT_REMOVE_LISTENER_SMALL_SCREEN = 'EVENT_REMOVE_LISTENER_SMALL_SCREEN',
    EVENT_REMOVE_LISTENER_SMALL_SCREEN_REVERSE = 'EVENT_REMOVE_LISTENER_SMALL_SCREEN_REVERSE',
    EVENT_REMOVE_LISTENERS_SMALL_SCREEN = 'EVENT_REMOVE_LISTENERS_SMALL_SCREEN',

    EVENT_REMOVE_LISTENERS_SCREEN = 'EVENT_REMOVE_LISTENERS_SCREEN'

export const EVENT_ADD_LISTENER_HOVERABLE = 'EVENT_ADD_LISTENER_HOVERABLE',
    EVENT_ADD_LISTENER_HOVERABLE_REVERSE = 'EVENT_ADD_LISTENER_HOVERABLE_REVERSE',
    EVENT_REMOVE_LISTENER_HOVERABLE = 'EVENT_REMOVE_LISTENER_HOVERABLE',
    EVENT_REMOVE_LISTENER_HOVERABLE_REVERSE = 'EVENT_REMOVE_LISTENER_HOVERABLE_REVERSE',
    EVENT_REMOVE_LISTENERS_HOVERABLE = 'EVENT_REMOVE_LISTENERS_HOVERABLE'

export const EVENT_ADD_LISTENER_TOUCHABLE = 'EVENT_ADD_LISTENER_TOUCHABLE',
    EVENT_ADD_LISTENER_TOUCHABLE_REVERSE = 'EVENT_ADD_LISTENER_TOUCHABLE_REVERSE',
    EVENT_REMOVE_LISTENER_TOUCHABLE = 'EVENT_REMOVE_LISTENER_TOUCHABLE',
    EVENT_REMOVE_LISTENER_TOUCHABLE_REVERSE = 'EVENT_REMOVE_LISTENER_TOUCHABLE_REVERSE',
    EVENT_REMOVE_LISTENERS_TOUCHABLE = 'EVENT_REMOVE_LISTENERS_TOUCHABLE'

export const EVENT_NAVIGATING = 'EVENT_NAVIGATING',
    EVENT_NAVIGATED = 'EVENT_NAVIGATED'

export const EVENT_PERFORM_RIPPLE_EFFECT = 'EVENT_PERFORM_RIPPLE_EFFECT',
    EVENT_PERFORM_RIPPLE_EFFECT_FOR_FRAMED_BUTTON = 'EVENT_PERFORM_RIPPLE_EFFECT_FOR_FRAMED_BUTTON'

export const EVENT_OPEN_LAMP = 'EVENT_OPEN_LAMP',
    EVENT_CLOSE_LAMP = 'EVENT_CLOSE_LAMP'

export const EVENT_OPEN_MODAL = 'EVENT_OPEN_MODAL',
    EVENT_CLOSE_LAST_MODAL = 'EVENT_CLOSE_LAST_MODAL',
    EVENT_CLOSE_ALL_MODALS = 'EVENT_CLOSE_ALL_MODALS'

export const EVENT_LOCK_SCREEN = 'EVENT_LOCK_SCREEN',
    EVENT_RELEASE_SCREEN = 'EVENT_RELEASE_SCREEN'

export const EVENT_ADD_INTERSECTION_OBSERVER = 'EVENT_ADD_OBSERVER',
    EVENT_REMOVE_INTERSECTION_OBSERVER = 'EVENT_REMOVE_OBSERVER'

export const EVENT_LOAD_LAZY_IMAGE = 'EVENT_LOAD_LAZY_IMAGE'

export const EVENT_SLIDER_LOADED = 'EVENT_SLIDER_NAVIGATION_LOAD',
    EVENT_SLIDER_NAVIGATION_TO_PREV = 'EVENT_SLIDER_NAVIGATION_TO_PREV',
    EVENT_SLIDER_NAVIGATION_TO_NEXT = 'EVENT_SLIDER_NAVIGATION_TO_NEXT',
    EVENT_SLIDER_SLIDE_TO_INDEX = 'EVENT_SLIDE_TO_INDEX',
    EVENT_SLIDER_INDEX_CHANGED = 'EVENT_SLIDER_INDEX_CHANGED',
    EVENT_SLIDER_INSERT_ELEMENTS_FOR_INFINITY = 'EVENT_SLIDER_INSERT_ELEMENTS_FOR_INFINITE'